// <auto-generated />
using System;
using ECOM.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECOM.Data.Migrations
{
    [DbContext(typeof(InitialDbContext))]
    [Migration("20200911145814_MelhoriasMapping")]
    partial class MelhoriasMapping
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECOM.API.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ECOM.API.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("Model")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("ProductsProductsId")
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductsProductsId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ECOM.Business.Models.ProductsProducts", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ProductFatherId")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ProductSonId")
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductFatherId");

                    b.HasIndex("ProductSonId");

                    b.ToTable("ProductsProducts");
                });

            modelBuilder.Entity("ECOM.API.Models.Product", b =>
                {
                    b.HasOne("ECOM.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.HasOne("ECOM.Business.Models.ProductsProducts", null)
                        .WithMany("Products")
                        .HasForeignKey("ProductsProductsId");
                });

            modelBuilder.Entity("ECOM.Business.Models.ProductsProducts", b =>
                {
                    b.HasOne("ECOM.API.Models.Product", "ProductFather")
                        .WithMany("ProductsProducts")
                        .HasForeignKey("ProductFatherId");

                    b.HasOne("ECOM.API.Models.Product", "ProductSon")
                        .WithMany()
                        .HasForeignKey("ProductSonId");
                });
#pragma warning restore 612, 618
        }
    }
}
